---
- name: "Check tmux"
  include_role:
    name: dotfiles-role-repo-installer
  vars:
    remote_url: https://github.com/tmux/tmux
    src_path: "{{ tmux_src_path }}"

# Included roles can't notify parent handlers
- name: "Trigger handler"
  command: /bin/true
  no_log: yes
  check_mode: no
  when: repo_update|changed
  changed_when: true
  notify: "rebuild tmux"
  tags:
    - skip_ansible_lint

- name: "Check tpm"
  include_role:
    name: dotfiles-role-repo-installer
  vars:
    remote_url: https://github.com/tmux-plugins/tpm
    src_path: "{{ config_dir }}/tmux/plugins/tpm"
    repo_owner: "{{ owning_user }}"
    repo_group: "{{ owning_group }}"
    repo_become: no

- name: "Template tmux config"
  include_role:
    name: dotfiles-role-generic-template
  vars:
    template_root: "{{ root_dir }}"
    template_path: ".tmux.conf"
